### ISSUE TITLE
asm

### ISSUE THREAD

**Issue by zandzpider** [ssimpson89/ffmpeg-installer#7]
Why would you disable asm? the fps drop while converting an x264 file would be HUUUUGE

**Comment by ssimpson89** [comment]
I believe that would be remnants of the original ffmpeg script. Which part of the code would you propose changing to enable asm?

**Comment by zandzpider** [comment]
jesus. that is my bad. i only saw the --disable-asm and didnt notice that it was commented out.
it WOULD be under compiling of  -------------- Installing x264 --------------.
Will fork this repo, and adjust it to work for ubuntu.

Thanks!
